#!/bin/bash

mkdir /etc/voat/
mkdir /etc/voat/db
mkdir /etc/voat/config

useradd voat
 
chown -R voat:voat /etc/voat
chmod -R 775       /etc/voat

echo "NOTE: Add yourself to the voat group (gpasswd -a [your_username] voat)"
echo "NOTE: Link the config to /etc/voat/config/config.json (ln -s [config_path_in_git_clone] /etc/voat/config/config.json)"
